-- =========================================================================
-- Carga inicial de clientes — Sierras de Aigua
-- Origen: planilla PDF "SIERRAS 2026, ventas montevideo.pdf"
-- Analisis y consolidacion validada por Rodrigo:
--   * Distribuidores (revendedores con margen propio): Julio de Armas,
--     Los Manzanos, Jenjibre, Tincho, Marce, MEGALABS.
--   * Deduplicaciones aplicadas: Ines/Maria Ines Uriarte, Beatriz
--     Carnelli/Cernelli, Antonio Corbi, Jorge Rolo (padre), Margarita
--     Ramirez, Florencia D'Ottone, Laura Baru, Jorge Goncalves, Denys,
--     Sofi Mandor, Colo Mateo, Adriana (ex SESA), Julio de Armas.
--   * NO deduplicados: Marce y Marcello (2), Ceci/Cecilia/Ceci Maciel (3),
--     Claudia y Claudia Garagorry (2), Fabi y Fabian (2).
--   * NO se cargan: yo, mama, aye, gonzu, emi, dani, fer, seba, chapi
--     (amigo), Rodri envios (cadete), Evento 11va cosecha.
-- Se dejan telefono/direccion vacios para completar despues desde el modulo.
-- Idempotente: si un nombre ya existe, no vuelve a insertarlo.
-- =========================================================================

-- Marcamos por nombre para evitar duplicados en cargas sucesivas.
create unique index if not exists idx_clientes_nombre_unique on public.clientes(nombre);

insert into public.clientes (nombre, tipo, notas) values
  -- ============ Distribuidores (revendedores) ============
  ('Julio de Armas',           'distribuidor', 'Revendedor. Compra frecuente en el campo: intenso, suave, miel, aceitunas. Pago efectivo. Muchas veces via Rodrigo envios.'),
  ('Los Manzanos',             'distribuidor', 'Revendedor. Compras grandes recurrentes ($30.000 efectivo). Pago a Santi. Granel y envasado.'),
  ('Jenjibre',                 'distribuidor', 'Revendedor. Compras grandes (12x1L suave, 6x1L intenso, 12x1/4). Saldos por planilla, a cuenta de Santiago.'),
  ('Tincho',                   'distribuidor', 'Revendedor. Compra intenso y SF en cajas.'),
  ('Marce',                    'distribuidor', 'Cliente empresarial / revendedor. Factura A5. 2x5L habitual. $13.706 por operacion.'),
  ('MEGALABS (Anibal Torres)', 'distribuidor', 'Cliente empresarial. Pedidos grandes en pack (50 packs en 2 facturas, $60.000).'),

  -- ============ Minoristas ============
  ('Adriana (ex SESA)',        'minorista', '3 suave. Retira. Aparece 2+ veces.'),
  ('Agustin Prieto',           'minorista', 'DAC a Rocha. Intenso, SF. 2+ compras.'),
  ('Ale Chapi',                'minorista', 'Referido por Chapi. Intenso, premio, SF.'),
  ('Aleman',                   'minorista', '3 intenso + jabon + miel.'),
  ('Alejandro Quagliatta',     'minorista', '3 intenso / suave. 2+ compras. Pago efectivo.'),
  ('Alexis Maly',              'minorista', '5 Elaia. 2+ compras.'),
  ('Alfredo Bianco',           'minorista', 'Compra en el campo. 3 suave / 2x3 suave. Retira.'),
  ('Amiga Nati',               'minorista', '3 suave.'),
  ('Ana',                      'minorista', '2x3 intenso / 3 premio. A cuenta Itau. Descontar del sueldo.'),
  ('Ana Paula',                'minorista', '3 suave + 3 intenso. Envio.'),
  ('Ana Viqueira',             'minorista', '3 intenso. Envio.'),
  ('Anita Leaniz',             'minorista', 'Familia. 3 suave + jabon. Envio.'),
  ('Anita y Carlos',           'minorista', '3 suave.'),
  ('Antonio Corbi',            'minorista', '3 intenso. Envio recurrente. Cobra efectivo Rodri envios.'),
  ('Ariel Fusible',            'minorista', '3x3 intenso / 3 SF. Cliente recurrente.'),
  ('Atistoy',                  'minorista', '3 intenso.'),
  ('Aurora Riet',              'minorista', '3 suave + 3 intenso + aceitunas negras. Envio.'),
  ('Bea',                      'minorista', '2x3 intenso + miel gr + 1L intenso. Envio.'),
  ('Beatriz Carnelli',         'minorista', '2x1L intenso. Envio a 2 direcciones distintas.'),
  ('Beatriz Moleri',           'minorista', 'Prado. 3 suave + aceitunas. Descontar del sueldo.'),
  ('Belen (Eliana)',           'minorista', '3 intenso. A cuenta de Gonzalo.'),
  ('Carlos Pecora',            'minorista', '3 premio. Envio. Adelanto Rodrigo envios.'),
  ('Ceci',                     'minorista', '3 suave / intenso. Envio.'),
  ('Ceci Maciel',              'minorista', '3 intenso. Envio.'),
  ('Cecilia',                  'minorista', '3 intenso. Envio.'),
  ('Cecilia mama Erra',        'minorista', '3 suave + 2 aceitunas. Envio, despues del mediodia.'),
  ('Chelo',                    'minorista', '1L suave + aceitunas + miel / 1 picual. Venta campo.'),
  ('Checha',                   'minorista', '3 suave / 1L suave.'),
  ('Chino',                    'minorista', '3 SF + 3/4 premio + 1/2 intenso.'),
  ('Claudia',                  'minorista', '2x3 intenso. Retira miercoles.'),
  ('Claudia Garagorry',        'minorista', '2x3 suave. Paga en 2 transferencias con Monica Garagorry.'),
  ('Colo',                     'minorista', '3 suave + miel gr + 4 jabon.'),
  ('Colo Mateo',               'minorista', '3 intenso. 2+ compras.'),
  ('Colo Futbol',              'minorista', '3 intenso.'),
  ('Coqui',                    'minorista', '3 intenso.'),
  ('Dani',                     'minorista', '2x pack + miel gr + 3 elaia + aceituna / 3 SF.'),
  ('Daniel Chan',              'minorista', '3 suave + 3/4 Premio + aceituna. Pago efectivo.'),
  ('Danilo',                   'minorista', '3x1L intenso. Envio. Adelanto rodrigo envios.'),
  ('Darisma Mancuso',          'minorista', '3 suave. Envio. Rodrigo envios cobra en efectivo.'),
  ('Denys',                    'minorista', '2x3 intenso. 2+ compras.'),
  ('Dibe',                     'minorista', '1L suave + 3/4L premiado + 1/2L intenso + 3 aceitunas.'),
  ('Eduardo Diaz',             'minorista', 'Pendiente confirmar pedido.'),
  ('Eduardo Reolon',           'minorista', '3 SF. 2+ compras.'),
  ('Eloisa Nogueira',          'minorista', '3 premio + aceituna + miel ch.'),
  ('Esteban Granero',          'minorista', '2x 1/2 L suave e intenso. Plata en caja de quiosco.'),
  ('Esteban Nin',              'minorista', '2x3 premio / suave. Envio entre 8 y 13h.'),
  ('Estrella',                 'minorista', '2x3 SF. Envio.'),
  ('Fabi',                     'minorista', 'Pack. Distinto de Fabian.'),
  ('Fabian',                   'minorista', 'Aceite 2026 (pendiente).'),
  ('Facu Alori',               'minorista', '1L intenso.'),
  ('Facu Calvo',               'minorista', '3 intenso.'),
  ('Fer amiga de Nati',        'minorista', '1L picual + aceituna.'),
  ('Fio gym aye',              'minorista', '1 picual.'),
  ('Flopa',                    'minorista', '3 intenso.'),
  ('Flor Chirico',             'minorista', '3 premio + 1 miel gr. Envio, despachar los lunes.'),
  ('Florencia D''Ottone',      'minorista', '3 premio + aceituna / 2x3 premio + 3 miel ch. Envio.'),
  ('Franceses',                'minorista', '3x pack + 7 jabones + premio 3/4 (regalo). Adelanto Rodrigo.'),
  ('Gabriel Pais',             'minorista', '3 premio. Descontar de sueldo.'),
  ('Gabriela Pose',            'minorista', '3 intenso + pack / 4x3 premio + 4 jabon. Envio.'),
  ('Gaston Bergara',           'minorista', '3 intenso. Envio.'),
  ('Giselle',                  'minorista', '1L picual habitual. Envio martes.'),
  ('Gonzalo (gordo)',          'minorista', '1L picual. Amigo del entorno.'),
  ('Graciela Santero',         'minorista', '3 suave + 2x aceituna.'),
  ('Graciela Silvestri',       'minorista', '3 premio + 3 intenso. Envio los viernes.'),
  ('Guille Fuentes',           'minorista', '2 x 5 ELAIA + 2 x 3 intenso + aceituna. Envio. Compra grande ($13.130).'),
  ('Guz',                      'minorista', 'Cliente esporadico.'),
  ('Helena Perez',             'minorista', '2x3 suave + 3 intenso + jabon. DAC a Piriapolis.'),
  ('Horacio',                  'minorista', '3 suave. Envio.'),
  ('Hugo',                     'minorista', '2x3 intenso.'),
  ('Hugo Lauretta',            'minorista', '5kg picual. Pago efectivo.'),
  ('Imanol',                   'minorista', '3 suave.'),
  ('Joaquin Lopez',            'minorista', '3 intenso. DAC a El Pinar.'),
  ('Jorge Goncalves',          'minorista', '3x3 suave / 4x3 suave. Envio.'),
  ('Jorge Ricci',              'minorista', 'Venta campo. Premio 3/4 + miel + jabon / 2x miel gr + 2x miel ch.'),
  ('Jorge Rolo (padre)',       'minorista', '3 suave habitual. 3+ compras.'),
  ('Juampi',                   'minorista', '3 suave.'),
  ('Juan Pedro Torres',        'minorista', '3 intenso.'),
  ('Juan primo Anita',         'minorista', '3 intenso. Envio por DAC.'),
  ('Juan Quimico',             'minorista', '20kg picual. Aceitunas.'),
  ('Karina',                   'minorista', '3 suave. DAC a Paso de los Toros.'),
  ('Karina Heat',              'minorista', 'Cliente referida por Chapi. 1 suave.'),
  ('Laura',                    'minorista', 'Compra grande en Latu (regalo empresa $35.720). Ver si consolida con Laura Latu.'),
  ('Laura Baru',               'minorista', '2x3 suave / 2x3 premio. Envio. 3+ compras.'),
  ('Laura Escuder',            'minorista', '3 intenso / 3 SF / 2x3 intenso + 1L picual. Envio jueves.'),
  ('Laura Latu',               'minorista', '6xpack. Envio (empresa Latu paga costo).'),
  ('Laura Passaro',            'minorista', '3 x pack. Envio (nosotros pagamos envio).'),
  ('Lavanca',                  'minorista', '3 intenso.'),
  ('Leandro',                  'minorista', '3 premio. Retira.'),
  ('Liber Garcia',             'minorista', '3 intenso.'),
  ('Lilian',                   'minorista', '2x3 premio. Envio.'),
  ('Llambi Aigua',             'minorista', '1L intenso. Plata en caja de quiosco.'),
  ('Lucia',                    'minorista', '3 intenso + 3 suave. Retira viernes 15hs.'),
  ('Lucy mama de Pablo Blanco','minorista', '3 suave. Repartir martes de manana.'),
  ('Maflo',                    'minorista', '3 suave.'),
  ('Manco',                    'minorista', 'Miel gr.'),
  ('Mandor',                   'minorista', '3/4 premio + 1L pic / 3 intenso + 3/4 premio. Descuento sueldo agosto.'),
  ('Marcello',                 'minorista', '2x3 intenso. Envio.'),
  ('Marga',                    'minorista', '3 premio + pack. Descontar del sueldo.'),
  ('Margarita Ramirez',        'minorista', '3 suave x 2. Envio.'),
  ('Maria Ines Uriarte',       'minorista', '3 suave + jabon / 3 premiado. Envio. 3+ compras.'),
  ('Maria Kriz',               'minorista', '3 suave + 3 intenso + jabon. DAC a La Floresta / Parque del Plata / Atlantida.'),
  ('Maria Victoria Landoni',   'minorista', '1 suave + pack + aceituna. Envio.'),
  ('Mari',                     'minorista', '1L suave. Pago a Itau de Rodri.'),
  ('Mariana Perez',            'minorista', '3 intenso / 3 premio. DAC a Shangrila.'),
  ('Mario Lozano',             'minorista', '3 suave. Envio.'),
  ('Marisel',                  'minorista', '3 SF. Dejar en cooperativa CALAI.'),
  ('Marisol',                  'minorista', '3 intenso. Retira lunes.'),
  ('Marisol Maidana',          'minorista', '5 Elaia. Dejar en Minas de pasada, miercoles.'),
  ('Mateo Colo',               'minorista', '3 intenso.'),
  ('Mauri',                    'minorista', '1 pack + 1 aceituna. Envio.'),
  ('Mauro Sotelo',             'minorista', '3 suave.'),
  ('Mauro y Checha',           'minorista', '1L suave. Podria ser pareja.'),
  ('Meli',                     'minorista', '3 intenso + pack + aceitunas. DAC a Soriano, Artigas 1022.'),
  ('Mercedes Bregante',        'minorista', '2x3 suave. Envio. 2+ compras.'),
  ('Mercedes Marra',           'minorista', '3 intenso. Envio. Tiene envio a favor.'),
  ('Merilex',                  'minorista', 'Pack x3 / 1L intenso.'),
  ('Michael Fox',              'minorista', 'Pendiente confirmar pedido.'),
  ('Miguel Chalupa',           'minorista', '5 ELAIA. Pago efectivo. Bulevar y Estole.'),
  ('Miriam De Oliveira',       'minorista', '2x1L picual + 3/4 premio + 1 aceituna.'),
  ('Monica Garagorry',         'minorista', 'SF 3/4 + premio 3/4. Ver si integrar con Claudia Garagorry.'),
  ('Nacho Ameneiros',          'minorista', '3 suave.'),
  ('Nacho Cerminara',          'minorista', '1L suave.'),
  ('Natalia',                  'minorista', '3 suave. Descontar a papa que cobro efectivo.'),
  ('Natalia Martinez',         'minorista', 'Pack (pendiente cobro).'),
  ('Natalie',                  'minorista', 'Pack + aceituna.'),
  ('Negro Anibal',             'minorista', '3 premiado / aceitunas. Retira.'),
  ('Nico Silvera',             'minorista', '2x3 intenso. 2+ compras.'),
  ('Nicolas Prudente',         'minorista', '3 intenso + aceituna. Paga con arreglo de heladera (canje).'),
  ('Pancho Massari',           'minorista', '2x3 suave.'),
  ('Pato Garagorry',           'minorista', '3 suave.'),
  ('Patricia',                 'minorista', '3 suave + 3 intenso + 3/4 premio + pack + miel gr.'),
  ('Pedro',                    'minorista', '3 intenso / 3x3/4 SF + 3 premio + 3 int.'),
  ('Pierino',                  'minorista', '1 L intenso. Quiosco campo.'),
  ('PIERR',                    'minorista', 'Pendiente confirmar pedido.'),
  ('Prima Ana',                'minorista', '3 suave + 1 jabon. Prima (falta apellido).'),
  ('Primo Mari',               'minorista', '3 intenso. Primo (falta apellido).'),
  ('Rata',                     'minorista', '3 premiado. Retira.'),
  ('Renzo Ghio',               'minorista', '3 suave. Retira.'),
  ('Rodri de Armas',           'minorista', '1L suave + miel gr. Distinto de distribuidor Julio de Armas.'),
  ('Rosario',                  'minorista', 'SF 3/4 + aceituna + miel gr. Enviar a El Pinar.'),
  ('Sandra',                   'minorista', '2x3 suave.'),
  ('Santi Simes',              'minorista', '1L picual + miel gr.'),
  ('Sara Maria vet Aigua',     'minorista', '2x3 suave. Plata en caja de quiosco.'),
  ('Seba di Candia',           'minorista', '2x3 SF + 3 suave.'),
  ('Sofi Mandor',              'minorista', '3 intenso. 3+ compras.'),
  ('Sol vecina Aye',           'minorista', '3 suave.'),
  ('Sylvia Penela',            'minorista', 'Pack + 3 premio. Repartir jueves.'),
  ('Tia Sabina',               'minorista', '2x3 suave. Envio.'),
  ('Tia Vero',                 'minorista', '3x3 suave + 3 intenso.'),
  ('Tito',                     'minorista', '3 suave. Trueque.'),
  ('Troco',                    'minorista', '3 intenso.'),
  ('Vale Amiga Aye',           'minorista', '3 premio + 3/4 premio + 1L picual + 3 aceituna + 2 miel ch.'),
  ('Vale Dos Sanjos',          'minorista', '2 x 1L picual. Enviar a oficina.'),
  ('Veronica Leys',            'minorista', '3 intenso. Envio jueves.'),
  ('Victoria Sallaberry',      'minorista', '2x3 premio + 2x3 intenso.'),
  ('Vina Eden',                'minorista', '100x1/2L + 2x3 suave. Cliente empresa.'),
  ('Viviana Misurraco',        'minorista', '3 Elaia.'),
  ('Yanira',                   'minorista', '3 intenso. Envio martes.'),
  ('Yola',                     'minorista', '3 intenso.'),
  ('Asolur',                   'minorista', '2x 1/2 L. Empresa.')
on conflict (nombre) do nothing;

-- Verificacion rapida
select tipo, count(*) as cantidad from public.clientes group by tipo order by tipo;
